//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiscPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiscPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Pauses to Device Time.
        /// </summary>
        internal static string Edit_AdjustPausesToDevice_Text {
            get {
                return ResourceManager.GetString("Edit_AdjustPausesToDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Rest Laps .
        /// </summary>
        internal static string Edit_DetectRestLaps_Text {
            get {
                return ResourceManager.GetString("Edit_DetectRestLaps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Track to GPS points.
        /// </summary>
        internal static string Edit_ElevationToGPS_Text {
            get {
                return ResourceManager.GetString("Edit_ElevationToGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To CompareTracks.
        /// </summary>
        internal static string Edit_ExportActivityToCompareTracks_Text {
            get {
                return ResourceManager.GetString("Edit_ExportActivityToCompareTracks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend GPS Track to Activity.
        /// </summary>
        internal static string Edit_ExtendGPS_Text {
            get {
                return ResourceManager.GetString("Edit_ExtendGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix initial HR spikes.
        /// </summary>
        internal static string Edit_FixHR_Text {
            get {
                return ResourceManager.GetString("Edit_FixHR_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix NaN in Tracks.
        /// </summary>
        internal static string Edit_FixNaN_Text {
            get {
                return ResourceManager.GetString("Edit_FixNaN_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Pauses at GPS Gaps.
        /// </summary>
        internal static string Edit_InsertPauses_Text {
            get {
                return ResourceManager.GetString("Edit_InsertPauses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Laps and Stops in CadenceTrack.
        /// </summary>
        internal static string Edit_Lap2Cadence_Text {
            get {
                return ResourceManager.GetString("Edit_Lap2Cadence_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveUpdate.
        /// </summary>
        internal static string Edit_LiveUpdate_Text {
            get {
                return ResourceManager.GetString("Edit_LiveUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Identical GPS Points While Moving.
        /// </summary>
        internal static string Edit_RemoveIdenticalGPS_Text {
            get {
                return ResourceManager.GetString("Edit_RemoveIdenticalGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time/Pace on GPS Points.
        /// </summary>
        internal static string Edit_SetTimeGPS_Text {
            get {
                return ResourceManager.GetString("Edit_SetTimeGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp.
        /// </summary>
        internal static string UI_Activities_PageControl_tmp_Text {
            get {
                return ResourceManager.GetString("UI_Activities_PageControl_tmp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiscPlugin.
        /// </summary>
        internal static string UI_Settings_MiscPluginPage_Title {
            get {
                return ResourceManager.GetString("UI_Settings_MiscPluginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate at Import.
        /// </summary>
        internal static string UI_Settings_PageControl_labelActivateAtImport_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelActivateAtImport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Pauses to Device Time.
        /// </summary>
        internal static string UI_Settings_PageControl_labelAdjustPausesToDevice_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelAdjustPausesToDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Pauses so the activity time matches the device time (or manually entered time).
        /// </summary>
        internal static string UI_Settings_PageControl_labelAdjustPausesToDeviceInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelAdjustPausesToDeviceInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Rest Laps.
        /// </summary>
        internal static string UI_Settings_PageControl_labelDetectRestLaps_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelDetectRestLaps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect rest laps. Currently only warmup and cooldown..
        /// </summary>
        internal static string UI_Settings_PageControl_labelDetectRestLapsInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelDetectRestLapsInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Menu.
        /// </summary>
        internal static string UI_Settings_PageControl_labelEditMenuItem_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelEditMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Track to GPS Points.
        /// </summary>
        internal static string UI_Settings_PageControl_labelElevationToGPS_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelElevationToGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the separate elevation track to the GPS track.
        /// </summary>
        internal static string UI_Settings_PageControl_labelElevationToGPSInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelElevationToGPSInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend GPS Track to Activity.
        /// </summary>
        internal static string UI_Settings_PageControl_labelExtendGPS_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelExtendGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend GPS Track to Activity Start/End if GPS track is shorter than the clock or heart rate track.
        /// </summary>
        internal static string UI_Settings_PageControl_labelExtendGPSInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelExtendGPSInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Pauses at GPS Gaps.
        /// </summary>
        internal static string UI_Settings_PageControl_labelInsertPauses_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelInsertPauses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert pauses if there are time gaps for the GPS points.
        /// </summary>
        internal static string UI_Settings_PageControl_labelInsertPausesInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelInsertPausesInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min GPS gap.
        /// </summary>
        internal static string UI_Settings_PageControl_labelInsertPausesWhenGPSdifferMinSeconds_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelInsertPausesWhenGPSdifferMinSeconds_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Identical GPS Points.
        /// </summary>
        internal static string UI_Settings_PageControl_labelRemoveIdenticalGPS_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelRemoveIdenticalGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove identical GPS points where the distance track indicates moving. (Fix for Edge 705 one second recording.).
        /// </summary>
        internal static string UI_Settings_PageControl_labelRemoveIdenticalGPSInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelRemoveIdenticalGPSInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time/Pace on GPS Points.
        /// </summary>
        internal static string UI_Settings_PageControl_labelSetTimeGPS_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelSetTimeGPS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the time on GPS points using the Distance track if it exists, otherwise using the activity time.
        /// </summary>
        internal static string UI_Settings_PageControl_labelSetTimeGPSInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelSetTimeGPSInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Webpage.
        /// </summary>
        internal static string UI_Settings_PageControl_linkInformativeUrl_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_linkInformativeUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://code.google.com/p/sporttracks-miscplugin/wiki/MiscPlugin.
        /// </summary>
        internal static string UI_Settings_PageControl_linkInformativeUrl_Url {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_linkInformativeUrl_Url", resourceCulture);
            }
        }
    }
}
