//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsCorrectionPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpsCorrectionPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust GPS from Device Distance.
        /// </summary>
        internal static string Edit_CorrectGPSFromDistance_Text {
            get {
                return ResourceManager.GetString("Edit_CorrectGPSFromDistance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put GPS-device Distance Diff in PowerTrack.
        /// </summary>
        internal static string Edit_DistanceDiffToPower_Text {
            get {
                return ResourceManager.GetString("Edit_DistanceDiffToPower_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GpsCorrection.
        /// </summary>
        internal static string UI_Settings_Page_Title {
            get {
                return ResourceManager.GetString("UI_Settings_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate at Import.
        /// </summary>
        internal static string UI_Settings_PageControl_labelActivateAtImport_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelActivateAtImport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust GPS from Device Distance.
        /// </summary>
        internal static string UI_Settings_PageControl_labelCorrectGPSFromDistance_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelCorrectGPSFromDistance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes GPS points that likely is incorrect by checking negative distances in the distance track.
        /// </summary>
        internal static string UI_Settings_PageControl_labelCorrectGPSFromDistanceInformative_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelCorrectGPSFromDistanceInformative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Menu.
        /// </summary>
        internal static string UI_Settings_PageControl_labelEditMenuItem_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_labelEditMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Webpage.
        /// </summary>
        internal static string UI_Settings_PageControl_linkInformativeUrl_Text {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_linkInformativeUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://code.google.com/p/sporttracks-miscplugin/wiki/GpsCorrection.
        /// </summary>
        internal static string UI_Settings_PageControl_linkInformativeUrl_Url {
            get {
                return ResourceManager.GetString("UI_Settings_PageControl_linkInformativeUrl_Url", resourceCulture);
            }
        }
    }
}
